create database batch79;
use batch79;
create table products(pid int,pname varchar(30) not null,brand varchar(30) not null,cmpname varchar(30) not null,price int not null,quantity int not null,primary key(pid));
insert into products values(1,'phone','vivo','abcd',40000,1),(2,'ear pods','oneplus','bcde',10000,1),(3,'dress','fig','cdef',2000,2),(4,'laptop','mac','efgh',80000,1);
insert into products values(5,'fridge','samsung','defg',50000,1);
select * from products;
update products set price=40000 where pname='vivo';
delete from products where pid=5;
set sql_safe_updates=0;
update products set price=5000;
